# Generated by Django 4.1.4 on 2023-03-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("availibilty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="booking",
            fields=[
                ("sr_no", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("mobile_no", models.BigIntegerField()),
                ("email", models.CharField(max_length=100)),
                ("checkin", models.DateField()),
                ("checkout", models.DateField()),
                (
                    "a_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="availibilty.rooms",
                    ),
                ),
            ],
        ),
    ]
