# Generated by Django 4.1.4 on 2023-05-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Q_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_report",
            name="cost_per_click",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="user_report",
            name="cost_per_day",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="user_report",
            name="cost_per_impressions",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="user_report",
            name="total_cost_per_click",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="user_report",
            name="total_cost_per_impressions",
            field=models.FloatField(),
        ),
    ]
