# Generated by Django 4.1.4 on 2023-05-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Q_app", "0002_alter_user_report_cost_per_click_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirements",
            name="planned_cost",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="requirements",
            name="planned_cpc",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="requirements",
            name="planned_cpm",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="requirements",
            name="planned_impressions",
            field=models.FloatField(),
        ),
    ]
